twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/public/front/images/email': emails
        '%kernel.project_dir%/public/front/css/email': bemails

when@test:
    twig:
        strict_variables: true
        form_themes: ['bootstrap_4_horizontal_layout.html.twig']

