vich_uploader:
    db_driver: orm
    mappings:
        picture_files:
            uri_prefix: /front/webfiles
            upload_destination: '%kernel.project_dir%/public/front/webfiles'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
