#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
  path: /logout
  methods: GET

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing-sf4.xml"